### ISSUE TITLE
Remove "Skipping - not selected" log line

### ISSUE THREAD

**Issue by turar** [MeltanoLabs/tap-salesforce#29]
It seems that [a single INFO log line](https://github.com/MeltanoLabs/tap-salesforce/blob/90459ed95454b02ec0ec2a9dfe74f78b455e6dc5/tap_salesforce/__init__.py#L426) in `tap-salesforce/__init__.py` is adding a lot of unneeded noise to our Meltano logs, and we suspect it's not useful to other users:

```Python
    if not stream_is_selected(mdata):
        LOGGER.info("%s: Skipping - not selected", stream_name)
        return
```

Would it be possible to remove it and just simply return in the if block above? 
cc: @tayloramurphy

**Comment by tayloramurphy** [comment]
@aaronsteers AFAIK this isn't something that we have as a best practice in the SDK, right? I'd be in favor of removing it. @dan-ladd any objections or concerns around this?

**Comment by dan-ladd** [comment]
It might make sense to downgrade this log to debug. That way it should cut down on the day-to-day noise.

**Comment by aaronsteers** [comment]
> It might make sense to downgrade this log to debug. That way it should cut down on the day-to-day noise.

Love this. Easy solution and I'm happy to submit the PR.

**Comment by aaronsteers** [comment]
@turar - Please reopen if you see further issue here. Thanks again for raising. 👍

**Comment by turar** [comment]
> @turar - Please reopen if you see further issue here. Thanks again for raising. 👍

Thank you all so much for getting this done so quickly! Our team would love to hear this news.
