### ISSUE TITLE
feat: Port `tap-salesforce` to the Meltano Singer SDK

### ISSUE THREAD

**Issue by kgpayne** [MeltanoLabs/tap-salesforce#33]
To make use of features such as `BATCH` messaging and the standards tests framework, we should consider porting this tap to the [SDK](https://sdk.meltano.com/).

**Comment by tayloramurphy** [comment]
This is now in progress!

**Comment by andyoneal** [comment]
> This is now in progress!

How's it going? Would love to test and contribute when you get it to that point.

**Comment by tayloramurphy** [comment]
@andyoneal we should have the repo live next week 😄

**Comment by andyoneal** [comment]
https://github.com/MeltanoLabs/tap-salesforce/tree/sdk

**Comment by kgpayne** [comment]
Thanks @andyoneal 🙌 Closing as completed 🚀

**Comment by maxmarcon** [comment]
Does this mean that this tap now supports the [stream_maps](https://sdk.meltano.com/en/latest/stream_maps.html) ?

I tried them with the latest version and the `stream_maps` configuration seems to be completely ignored. Can someone please confirm or refute that `stream_maps` are available? 

Thanks
