### ISSUE TITLE
Built wheel for tap-salesforce is invalid: Metadata 1.2 mandates PEP 440 version, but 'meltano.1.5.0' is not

### ISSUE THREAD

**Issue by JazzLikeFruit** [MeltanoLabs/tap-salesforce#38]
Hi, 

I'm getting this error when trying to install this project. Do you know what could be causing it? 

Thanks in advance.

**Comment by WillDaSilva** [comment]
Hi @JazzLikeFruit. This should be fixed by:
- https://github.com/MeltanoLabs/tap-salesforce/pull/37

Are you using the latest version of this tap (`v1.5.1`)?

**Comment by JazzLikeFruit** [comment]
Hi @WillDaSilva I'm running pip install git+https://gitlab.com/meltano/tap-salesforce.git which is giving me this error

**Comment by JazzLikeFruit** [comment]
pip install git+https://gitlab.com/meltano/tap-salesforce.git@v1.5.1 does not run. I got `WARNING: Did not find branch or tag 'v1.5.1', assuming revision or ref.`

**Comment by JazzLikeFruit** [comment]
The instructions in the readme file include an incorrect link `https://gitlab.com/meltano/tap-salesforce.git` using `https://github.com/MeltanoLabs/tap-salesforce.git` worked for me.
