### ISSUE TITLE
FULL-TABLE replication only returning one row

### ISSUE THREAD

**Issue by JazzLikeFruit** [MeltanoLabs/tap-salesforce#40]
I changed the replication method of the AnalyticsBotSession object to full table but when executing I only get one row.

I added the following in the config file. 

        {
          "breadcrumb": [],
          "metadata": {
            "forced-replication-method": "FULL_TABLE",
            "table-key-properties": [
              "Id"
            ],
            "selected": true
          }
        }

**Comment by JazzLikeFruit** [comment]
@taylormurphy no I wasn't able to load the (analyticsbotsession) object incrementally, but we decided to not use that object anymore. Out of curiosity do you know what could have caused this issue? We are now missing two columns of another object (opportunityfieldhistory), So I will try to fully load that one.

**Comment by tayloramurphy** [comment]
> Out of curiosity do you know what could have caused this issue? 

@JazzLikeFruit unfortunately no - I will say that we're rewriting this tap on our SDK which will make debugging things like this way easier. The code for this current repo is quite old and not as stable as we would like.
