### ISSUE TITLE
HTTPError 406 CustomNotAcceptable encountered intermittently

### ISSUE THREAD

**Issue by haleemur** [MeltanoLabs/tap-salesforce#58]
# Description

We sometimes encounter the following error during discovery.

```
requests.exceptions.HTTPError: 406 Client Error: CustomNotAcceptable for url: https://XXX.salesforce.com/services/data/v53.0/sobjects/XXX/describe
```

However, on retrying manually, the taps runs fine. We believe this is an intermittent failure & perhaps salesforce is reporting an incorrect error, thereby masking the true cause of failure.

Since the error is recovered through retries, I feel that its probably good to add this error to backoff's list of exceptions to retry on.

**Comment by haleemur** [comment]
This seems may possibly be related to the following known issue

https://issues.salesforce.com/issue/a028c00000uYjIJAA0/accept-header-specified-in-http-request-is-not-supported-406-not-acceptable-error-in-the-apex-rest

**Comment by philwhln** [comment]
We're hitting this as well with the Salesforce API and we don't use tap-salesforce (we make direct requests). It started about 3 days ago. Very intermittent, even with identical requests.
